# Generated by Django 5.1.7 on 2025-05-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
