# Generated by Django 5.1.7 on 2025-05-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0002_customer_isverified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeId', models.CharField(max_length=20)),
                ('buyerId', models.CharField(max_length=20)),
                ('sellerId', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('rates', models.CharField(max_length=10)),
                ('time', models.DateTimeField(auto_now=True)),
                ('successful', models.BooleanField(blank=True, null=True)),
                ('buyerRating', models.CharField(blank=True, max_length=1, null=True)),
                ('sellerRating', models.CharField(blank=True, max_length=1, null=True)),
                ('timeToProcess', models.CharField(max_length=5)),
            ],
        ),
    ]
