# Generated by Django 5.1.7 on 2025-05-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0004_trade_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
