# Generated by Django 5.1.7 on 2025-05-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0005_customer_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='processingTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
