# Generated by Django 5.1.7 on 2025-05-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0006_customer_processingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='trades',
            field=models.IntegerField(default=0),
        ),
    ]
