# Generated by Django 5.1.7 on 2025-05-12 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0007_customer_trades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=1)),
                ('min_amount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('rates', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashienrest.customer')),
            ],
        ),
    ]
