# Generated by Django 5.1.7 on 2025-05-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0008_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='adId',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
