# Generated by Django 5.1.7 on 2025-05-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0009_ad_adid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='isBot',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='adId',
            field=models.CharField(max_length=30),
        ),
    ]
