# Generated by Django 5.1.7 on 2025-05-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0010_customer_isbot_alter_ad_adid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='isBot',
            field=models.BooleanField(),
        ),
    ]
