# Generated by Django 5.1.7 on 2025-05-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0011_alter_customer_isbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
