# Generated by Django 5.1.7 on 2025-05-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0012_customer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='timeToProcess',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
