# Generated by Django 5.1.7 on 2025-05-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0013_alter_trade_timetoprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_net', models.CharField(max_length=20)),
                ('wallet_address', models.CharField(max_length=50)),
            ],
        ),
    ]
