# Generated by Django 5.1.7 on 2025-05-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0014_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emailVerified',
            field=models.BooleanField(default = False),
        ),
        migrations.AddField(
            model_name='customer',
            name='idDocs',
            field=models.ImageField(blank=True, null=True, upload_to='verid'),
        ),
        migrations.AddField(
            model_name='customer',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='verselfie'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='isBot',
            field=models.BooleanField(default=False),
        ),
    ]
