# Generated by Django 5.1.7 on 2025-05-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0015_customer_emailverified_customer_iddocs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='emailVerified',
            field=models.BooleanField(default = False),
        ),
    ]
