# Generated by Django 5.1.7 on 2025-05-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0016_alter_customer_emailverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='emailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
