# Generated by Django 5.1.7 on 2025-05-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0017_alter_customer_emailverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vcode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
