# Generated by Django 5.1.7 on 2025-05-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0018_customer_vcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempIDVer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_doc', models.ImageField(upload_to='id')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cashienrest.customer')),
            ],
        ),
    ]
