# Generated by Django 5.1.7 on 2025-05-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0019_tempidver'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='idApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='selfieApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TempIDVer',
        ),
    ]
