# Generated by Django 5.1.7 on 2025-05-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0020_customer_idapproved_customer_selfieapproved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='isVerified',
        ),
    ]
