# Generated by Django 5.1.7 on 2025-05-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0021_remove_customer_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='account_number',
            field=models.CharField(default=27363728828282, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='bank_name',
            field=models.TextField(default='Dummy bank name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='receiver_name',
            field=models.TextField(default='dummy reciver name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
