# Generated by Django 5.1.7 on 2025-05-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0022_trade_account_number_trade_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
