# Generated by Django 5.1.7 on 2025-05-21 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0023_alter_trade_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=50)),
                ('message_text', models.TextField()),
                ('for_buyer', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashienrest.customer')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashienrest.trade')),
            ],
        ),
    ]
