# Generated by Django 5.1.7 on 2025-05-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0024_templatemessage_trademessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='cashien/receipts'),
        ),
    ]
