# Generated by Django 5.1.7 on 2025-05-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0025_customer_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='receipt',
        ),
        migrations.AddField(
            model_name='trade',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='cashien/receipts'),
        ),
    ]
