# Generated by Django 5.1.7 on 2025-05-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0026_remove_customer_receipt_trade_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
