# Generated by Django 5.1.7 on 2025-05-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0027_alter_trade_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
