# Generated by Django 5.1.7 on 2025-05-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0031_walletaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletAddress',
        ),
    ]
