# Generated by Django 5.1.7 on 2025-05-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0032_delete_walletaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_address', models.TextField()),
                ('is_deposit', models.BooleanField()),
            ],
        ),
    ]
