# Generated by Django 5.1.7 on 2025-05-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0033_depositrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepositRequest',
            new_name='TransactionRequest',
        ),
    ]
