# Generated by Django 5.1.7 on 2025-05-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0034_rename_depositrequest_transactionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrequest',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
