# Generated by Django 5.1.7 on 2025-05-28 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0036_transactionrequest_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrequest',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cashienrest.customer'),
            preserve_default=False,
        ),
    ]
