# Generated by Django 5.1.7 on 2025-05-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0037_transactionrequest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrequest',
            name='transaction_id',
            field=models.CharField(default=873778348783473847849873, max_length=30),
            preserve_default=False,
        ),
    ]
