# Generated by Django 5.1.7 on 2025-05-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0039_ad_terms_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='alipay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='bank',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='payoneer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='paypal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='remitly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='revolut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='sepa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='swift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='wechatpay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='wise',
            field=models.BooleanField(default=False),
        ),
    ]
