# Generated by Django 5.1.7 on 2025-05-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0040_ad_alipay_ad_bank_ad_payoneer_ad_paypal_ad_remitly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='receiver_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
