# Generated by Django 5.1.7 on 2025-05-31 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0041_trade_qr_code_alter_trade_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dispute')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashienrest.customer')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashienrest.trade')),
            ],
        ),
    ]
