# Generated by Django 5.1.7 on 2025-05-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0042_disputemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputemessage',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
