# Generated by Django 5.1.7 on 2025-06-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0043_disputemessage_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputemessage',
            name='is_sent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trademessage',
            name='is_sent',
            field=models.BooleanField(default=True),
        ),
    ]
