# Generated by Django 5.1.7 on 2025-06-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0044_disputemessage_is_sent_trademessage_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputemessage',
            name='msg_id',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
    ]
