# Generated by Django 5.1.7 on 2025-06-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0045_disputemessage_msg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='is_disputed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
