# Generated by Django 5.1.7 on 2025-06-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0046_trade_is_disputed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ratings',
            field=models.FloatField(default=8.0),
            preserve_default=False,
        ),
    ]
