# Generated by Django 5.1.7 on 2025-06-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0047_alter_customer_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ratings',
            field=models.FloatField(default=8.0),
        ),
    ]
