# Generated by Django 5.1.7 on 2025-06-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0049_alter_customer_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
