# Generated by Django 5.1.7 on 2025-06-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashienrest', '0050_customer_is_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vcode_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
